wne,wn,sne,swn,ne,wn,n,sne,wn,sn,sne,wne
sw,e,wn,sne,w,se,sw,n,s,sn,ne,we
swn,e,sw,sn,s,sn,sne,swe,wn,ne,sw,e
swn,,sne,wne,wn,n,sne,wne,swe,w,sn,e
swn,e,swn,s,,s,ne,w,n,s,ne,swe
wn,se,swn,n,s,sne,sw,se,swe,wne,w,ne
w,ne,wne,w,sne,wn,sne,swn,sn,e,we,swe
swe,w,,se,wn,e,wn,sn,n,s,,sne
swn,s,s,sn,se,swe,sw,sne,sw,sne,sw,sne
