wn,n,ne,swn,sn,n,sn,n,ne,wne,swn,sn,n,n,ne,swn,ne,wn,n,sn,sn,ne,wne,wne
we,w,se,wne,swn,,ne,w,e,w,ne,wne,we,swe,sw,ne,sw,se,we,wn,ne,swe,w,e
swe,w,sn,s,ne,swe,we,we,sw,s,s,s,se,swn,sn,e,wne,swn,e,we,sw,ne,we,swe
wn,se,wn,ne,swe,wn,e,sw,sne,wn,ne,wne,swn,ne,wn,s,s,n,se,w,ne,w,s,sne
we,wne,w,se,wn,se,sw,sne,wn,se,sw,,ne,sw,e,swn,ne,swe,wne,we,we,w,sn,sne
w,e,we,wne,swe,swn,n,n,,sn,ne,swe,w,ne,we,swn,s,n,se,swe,swe,w,n,sne
we,swe,we,sw,n,sne,swe,swe,swe,swn,se,wn,s,e,w,n,sne,w,ne,wn,sne,swe,we,wne
we,wn,,sne,we,wne,swn,ne,wn,sne,wn,s,ne,swe,we,swe,swn,e,swe,sw,sn,n,,e
we,swe,w,sn,,se,wn,s,e,wn,se,wn,se,swn,s,sn,n,s,sne,wne,wn,se,sw,e
sw,n,,sne,sw,sne,we,wne,w,,ne,w,sn,sne,wne,wne,w,sne,wn,e,sw,sn,ne,swe
swn,se,we,wne,wn,sne,w,se,we,swe,swe,we,wne,swn,,s,,n,se,swe,swn,sn,e,wne
wn,sne,w,e,sw,sn,s,ne,we,wn,sne,w,s,sn,s,sne,swe,swe,wne,swn,ne,swn,s,e
sw,sn,,e,swn,ne,wne,we,sw,,sne,w,n,ne,swn,n,sn,ne,we,wn,,n,sn,e
swn,n,se,we,wne,sw,e,we,swn,e,wne,swe,swe,w,n,e,swn,e,sw,s,se,we,swn,se
wn,s,ne,sw,s,sn,,e,wne,swe,w,sn,sne,swe,swe,swe,wne,sw,sn,ne,wne,w,sn,ne
w,sne,we,wn,n,sn,e,sw,e,swn,,sn,n,sn,n,sne,we,wne,wn,,s,se,wne,swe
sw,ne,swe,swe,sw,ne,swe,swn,e,wne,sw,sne,we,wne,w,ne,w,,se,w,n,n,se,wne
swn,s,sne,swn,sn,s,sne,swn,s,s,sn,sn,s,se,swe,swe,swe,swe,swn,se,swe,sw,sn,se
