wn,n,n,sn,sn,n,sne,wne,wne,swn,sn,sn,sn,ne,wne,wn,sn,n,sn,ne
swe,we,swe,wn,ne,sw,n,se,we,wn,sne,wne,wne,w,,s,sne,w,ne,swe
wne,w,sn,e,w,sne,swe,wn,s,se,swn,,s,se,swe,wne,wne,swe,w,sne
sw,se,wn,e,swe,swn,sn,e,swn,sn,sn,s,n,sne,swn,s,,sn,,sne
wn,sne,swe,sw,n,n,n,e,wn,sne,swn,sn,e,wn,ne,wne,w,sne,w,sne
w,sn,sne,swn,se,w,se,sw,,n,sn,sn,,se,sw,se,we,wn,s,ne
w,sn,sne,wn,sne,we,wn,sn,se,sw,ne,wne,w,n,sne,wne,swe,we,wne,swe
sw,sn,n,s,sne,swe,sw,ne,wn,sne,swe,we,swe,sw,n,,ne,swe,we,wne
wn,sn,se,wne,wne,wn,n,e,sw,ne,wn,,n,ne,we,sw,s,ne,w,se
sw,ne,wn,se,sw,se,we,sw,sn,se,swe,w,,se,we,wne,swn,e,we,wne
swn,,se,swn,ne,wn,s,sn,sn,n,n,s,s,ne,swe,w,n,se,we,we
wn,s,sn,sn,s,,sne,wne,wne,sw,e,swn,ne,swe,swn,e,we,wn,s,e
w,sne,wne,wn,ne,sw,n,e,sw,ne,swe,wn,se,swn,ne,swe,sw,e,swn,e
we,wn,e,we,swe,wn,se,w,n,,sn,se,wne,wn,,sn,n,se,wn,e
swe,swe,sw,s,sn,s,sne,swe,swe,swe,swn,sn,s,se,sw,sne,sw,sne,swe,swe
