swn,ne,wn,sn,sn,n,sn,sn,sne,swn,sn,n,n,n,sne,wn,sn,sne,swn,sn,sn,sn,n,sne,swn,n,n,sne
wne,w,se,wn,ne,swe,wn,n,sn,n,sne,swe,swe,w,ne,we,swn,n,n,sne,wn,sn,se,wn,sne,we,swe,wne
w,s,sn,se,sw,n,se,swe,swn,se,swn,sn,ne,w,,s,sn,se,sw,sn,se,wne,swn,s,n,s,sne,we
sw,n,sne,swn,n,se,swn,sn,n,sn,n,sne,we,w,e,swn,n,n,sne,wn,sn,e,wn,sn,s,n,n,se
wne,we,wne,wne,we,wne,wn,ne,sw,sne,sw,ne,we,swe,w,sn,e,swe,wn,se,wne,w,s,ne,wne,swe,swe,wne
sw,,se,w,s,e,we,w,sne,wne,swn,,se,wn,e,swn,e,wne,swe,swn,e,we,wne,sw,s,n,ne,we
swn,e,swn,se,swn,s,se,sw,n,s,ne,w,ne,swe,we,swn,s,e,wne,wn,s,s,s,n,sn,s,s,se
swn,e,swn,n,n,sne,wne,wne,we,swn,se,w,e,wn,se,swn,n,e,sw,se,swn,sn,sn,e,swn,n,sne,wne
wn,s,sn,e,we,wn,s,s,s,n,n,,e,w,ne,wne,swe,we,wn,sn,n,sn,ne,w,sn,e,swn,e
w,n,sne,swe,we,swe,wn,sne,wne,we,we,we,sw,e,sw,e,wn,s,,sne,sw,ne,swe,sw,ne,w,sn,e
we,we,swn,ne,sw,sn,s,sne,w,se,swe,we,swn,,ne,swe,swe,wn,se,swn,ne,we,wne,swn,e,swe,wne,we
we,sw,n,,n,n,sn,sne,w,sne,swn,s,ne,swe,swe,swn,sn,e,wne,swn,s,s,s,sne,we,wne,sw,e
we,swn,se,swe,swe,w,sne,swn,se,wn,sn,ne,sw,sn,sn,sne,wn,se,sw,n,sn,sne,swn,sn,e,w,sne,swe
w,n,sne,wne,wn,e,wne,swn,sn,,sne,we,swn,sn,n,sn,,n,n,se,wne,wne,wn,sne,w,s,sne,wne
w,se,wn,e,swe,sw,s,ne,swn,,sne,swe,wn,sn,se,wne,w,e,w,n,s,s,,n,se,wne,wne,we
we,wne,w,se,wne,wne,wne,swe,wn,s,ne,wne,we,wne,wn,se,we,swe,swe,w,ne,wne,we,swe,swn,s,s,e
w,,,n,se,we,w,sne,w,sne,w,s,s,se,w,ne,sw,n,sne,swe,we,w,s,n,n,n,sn,e
swe,we,we,sw,sn,e,we,swn,se,wne,we,wne,wn,n,se,sw,ne,sw,sne,wne,we,sw,ne,swe,swe,we,wne,we
wne,we,we,wne,swn,e,w,n,sne,we,sw,,,s,n,sne,sw,n,sn,se,we,wne,w,sne,wne,we,we,we
we,swe,sw,e,wne,w,se,sw,ne,sw,sn,,se,swn,e,swn,sn,e,wne,wn,se,sw,,sne,w,e,sw,se
sw,sn,sn,se,sw,s,sne,swn,s,sne,swn,se,swn,sn,s,sn,sne,sw,se,swe,swn,sn,se,swn,se,sw,sn,sne
